import {
  App,
  Notice,
  Plugin,
  PluginSettingTab,
  Setting,
  TFile,
} from "obsidian";

interface ForgeBridgeSettings {
  // Name of the index file regenerated by this plugin
  indexFileName: string;
  // Auto-regenerate the index when a MEMORY.md file is modified
  autoRefreshOnModify: boolean;
  // Limit Forge MEMORY.md scan to files literally named "MEMORY.md"
  // (default true to match Forge convention)
  scanOnlyMemoryMd: boolean;
}

const DEFAULT_SETTINGS: ForgeBridgeSettings = {
  indexFileName: "_forge-index.md",
  autoRefreshOnModify: false,
  scanOnlyMemoryMd: true,
};

interface ForgeSubject {
  name: string;
  type: string | null;
  forgingState: string | null;
  filePath: string; // vault-relative path of the MEMORY.md
  linkedSubjects: string[]; // raw slugs from frontmatter
}

export default class ForgeBridgePlugin extends Plugin {
  settings!: ForgeBridgeSettings;

  async onload(): Promise<void> {
    await this.loadSettings();

    this.addCommand({
      id: "forge-bridge-refresh-index",
      name: "Refresh Forge subject index",
      callback: () => this.refreshIndex(),
    });

    this.addCommand({
      id: "forge-bridge-show-stats",
      name: "Show Forge subject pool stats",
      callback: () => this.showStats(),
    });

    if (this.settings.autoRefreshOnModify) {
      this.registerEvent(
        this.app.vault.on("modify", (file) => {
          if (file instanceof TFile && file.name === "MEMORY.md") {
            this.refreshIndex();
          }
        })
      );
    }

    this.addSettingTab(new ForgeBridgeSettingTab(this.app, this));
  }

  onunload(): void {
    // Nothing to clean up — the index file is left on disk intentionally.
  }

  async loadSettings(): Promise<void> {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }

  async saveSettings(): Promise<void> {
    await this.saveData(this.settings);
  }

  // ------- Core: scan + index ------------------------------------------------

  private async scanSubjects(): Promise<ForgeSubject[]> {
    const subjects: ForgeSubject[] = [];
    const files = this.app.vault.getMarkdownFiles();

    for (const file of files) {
      if (this.settings.scanOnlyMemoryMd && file.name !== "MEMORY.md") {
        continue;
      }
      const content = await this.app.vault.cachedRead(file);
      const fm = parseFrontmatter(content);
      if (!fm || !fm["forging_state"]) {
        // Not a Forge subject
        continue;
      }
      subjects.push({
        name: String(fm["name"] || file.parent?.name || file.basename),
        type: fm["type"] ? String(fm["type"]) : null,
        forgingState: fm["forging_state"] ? String(fm["forging_state"]) : null,
        filePath: file.path,
        linkedSubjects: extractLinkedSubjects(fm["linked_subjects"]),
      });
    }
    return subjects;
  }

  async refreshIndex(): Promise<void> {
    const subjects = await this.scanSubjects();
    if (subjects.length === 0) {
      new Notice("Forge Bridge: no Forge subjects found in this vault.");
      return;
    }
    const md = renderIndexMarkdown(subjects);
    const indexPath = this.settings.indexFileName;
    const existing = this.app.vault.getAbstractFileByPath(indexPath);

    if (existing instanceof TFile) {
      await this.app.vault.modify(existing, md);
    } else {
      await this.app.vault.create(indexPath, md);
    }
    new Notice(`Forge Bridge: indexed ${subjects.length} subjects → ${indexPath}`);
  }

  async showStats(): Promise<void> {
    const subjects = await this.scanSubjects();
    const byState: Record<string, number> = {};
    const byType: Record<string, number> = {};
    let linkedCount = 0;
    for (const s of subjects) {
      const st = normalizeState(s.forgingState);
      byState[st] = (byState[st] || 0) + 1;
      const t = s.type || "(no type)";
      byType[t] = (byType[t] || 0) + 1;
      linkedCount += s.linkedSubjects.length;
    }
    const lines = [
      `Forge subjects: ${subjects.length}`,
      `Linked edges: ${linkedCount}`,
      "States: " + Object.entries(byState).map(([k, v]) => `${k}=${v}`).join(", "),
      "Types: " + Object.entries(byType).map(([k, v]) => `${k}=${v}`).join(", "),
    ];
    new Notice(lines.join("\n"), 10000);
  }
}

// -------- Frontmatter parsing (tolerant, stdlib-only) -----------------------

/** Minimal YAML frontmatter parser. Covers the subset used by Forge MEMORY.md.
 * Handles scalar lines `key: value` and inline lists `key: [a, b, c]`.
 * Block lists are parsed if items appear as `  - value` on subsequent lines.
 * Anything more exotic (nested dicts) is preserved as-is in the value string —
 * downstream consumers only need name/type/forging_state/linked_subjects.
 */
function parseFrontmatter(content: string): Record<string, unknown> | null {
  if (!content.startsWith("---")) return null;
  const end = content.indexOf("\n---", 4);
  if (end < 0) return null;
  const raw = content.slice(4, end);
  const result: Record<string, unknown> = {};
  const lines = raw.split("\n");
  let currentKey: string | null = null;
  let currentList: string[] | null = null;

  for (const line of lines) {
    if (!line.trim() || line.trim().startsWith("#")) continue;

    // Block list item
    if ((line.startsWith("  - ") || line.startsWith("    - ")) && currentList) {
      currentList.push(line.replace(/^\s*-\s*/, "").trim());
      continue;
    }

    // Top-level key
    if (!line.startsWith(" ") && line.includes(":")) {
      const idx = line.indexOf(":");
      const key = line.slice(0, idx).trim();
      const value = line.slice(idx + 1).trim();
      currentKey = key;
      if (!value) {
        const list: string[] = [];
        result[key] = list;
        currentList = list;
      } else if (value.startsWith("[") && value.endsWith("]")) {
        const inner = value.slice(1, -1).trim();
        result[key] = inner ? inner.split(",").map((s) => s.trim()) : [];
        currentList = null;
      } else {
        result[key] = stripQuotes(value);
        currentList = null;
      }
    }
  }
  return result;
}

function stripQuotes(s: string): string {
  if ((s.startsWith('"') && s.endsWith('"')) || (s.startsWith("'") && s.endsWith("'"))) {
    return s.slice(1, -1);
  }
  return s;
}

function extractLinkedSubjects(raw: unknown): string[] {
  if (!raw) return [];
  if (Array.isArray(raw)) {
    return raw.map((x) => String(x).trim()).filter((x) => x.length > 0);
  }
  if (typeof raw === "string") {
    return raw.split(",").map((x) => x.trim()).filter((x) => x.length > 0);
  }
  return [];
}

// -------- Cycle γ legacy normalization --------------------------------------

const LEGACY_STATE_MAP: Record<string, string> = {
  seed: "actif", debating: "actif", tentative: "actif",
  stress_testing: "mature", doctrine: "mature",
  in_service: "mature", under_review: "mature",
  archived: "archived", actif: "actif", mature: "mature",
};

function normalizeState(s: string | null): string {
  if (!s) return "unknown";
  return LEGACY_STATE_MAP[s] || s;
}

// -------- Markdown rendering of the index -----------------------------------

function slugFor(subject: ForgeSubject): string {
  // Canonical Forge slug: `<type>:<name>`. Fallback to bare name.
  return subject.type ? `${subject.type}:${subject.name}` : subject.name;
}

function renderIndexMarkdown(subjects: ForgeSubject[]): string {
  const lines: string[] = [];
  lines.push("# Forge Subject Index");
  lines.push("");
  lines.push("_Auto-generated by the Forge Bridge plugin. Do not edit by hand — "
    + "this file is overwritten on each refresh._");
  lines.push("");

  // Group by normalized state
  const groups: Record<string, ForgeSubject[]> = { actif: [], mature: [], archived: [], unknown: [] };
  for (const s of subjects) {
    const state = normalizeState(s.forgingState);
    if (!groups[state]) groups[state] = [];
    groups[state].push(s);
  }

  for (const state of ["actif", "mature", "archived", "unknown"]) {
    const items = groups[state] || [];
    if (items.length === 0) continue;
    lines.push(`## ${state} (${items.length})`);
    lines.push("");
    for (const s of items.sort((a, b) => a.name.localeCompare(b.name))) {
      const slug = slugFor(s);
      const noteLink = `[[${s.filePath}|${slug}]]`;
      const linkedRendered = s.linkedSubjects
        .map((l) => `[[${l}]]`)
        .join(", ");
      const tail = linkedRendered ? ` — links: ${linkedRendered}` : "";
      lines.push(`- ${noteLink}${tail}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

// -------- Settings tab ------------------------------------------------------

class ForgeBridgeSettingTab extends PluginSettingTab {
  plugin: ForgeBridgePlugin;

  constructor(app: App, plugin: ForgeBridgePlugin) {
    super(app, plugin);
    this.plugin = plugin;
  }

  display(): void {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Forge Bridge" });

    new Setting(containerEl)
      .setName("Index file name")
      .setDesc("Vault-relative path of the regenerated index file.")
      .addText((text) =>
        text
          .setPlaceholder("_forge-index.md")
          .setValue(this.plugin.settings.indexFileName)
          .onChange(async (value) => {
            this.plugin.settings.indexFileName = value.trim() || DEFAULT_SETTINGS.indexFileName;
            await this.plugin.saveSettings();
          })
      );

    new Setting(containerEl)
      .setName("Auto-refresh on MEMORY.md modify")
      .setDesc("Regenerate the index whenever a MEMORY.md file changes. "
        + "Disable if the vault is large and the scan becomes noisy.")
      .addToggle((toggle) =>
        toggle
          .setValue(this.plugin.settings.autoRefreshOnModify)
          .onChange(async (value) => {
            this.plugin.settings.autoRefreshOnModify = value;
            await this.plugin.saveSettings();
          })
      );

    new Setting(containerEl)
      .setName("Scan only MEMORY.md files")
      .setDesc("Restrict the subject scan to files literally named MEMORY.md "
        + "(matches the Forge convention). Disable to scan every markdown file "
        + "with a `forging_state` frontmatter key.")
      .addToggle((toggle) =>
        toggle
          .setValue(this.plugin.settings.scanOnlyMemoryMd)
          .onChange(async (value) => {
            this.plugin.settings.scanOnlyMemoryMd = value;
            await this.plugin.saveSettings();
          })
      );
  }
}
